# Generated by Django 2.2.3 on 2020-01-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_mode',
            field=models.CharField(choices=[('A', 'Airtel'), ('C', 'Cooperative'), ('V', 'Visa'), ('M', 'Mpesa'), ('P', 'Paypal'), ('K', 'Krep'), ('U', 'Unknown')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='PaymentsTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesapal_merchant_reference', models.CharField(max_length=100)),
                ('pesapal_transaction_tracking_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
            ],
        ),
    ]
