# Generated by Django 2.2.3 on 2019-08-15 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('cost_of_cards', models.FloatField(default=0)),
                ('transport_fee', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('receiver_fname', models.CharField(max_length=100, null=True)),
                ('receiver_lname', models.CharField(max_length=100, null=True)),
                ('total_no_of_card_batches', models.IntegerField(default=0)),
                ('mobile_no', models.IntegerField(default=0)),
                ('no_of_regular_batches', models.IntegerField(default=0)),
                ('no_of_premium_batches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Town')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
