# Generated by Django 2.2.3 on 2019-08-05 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('payment_status', models.IntegerField(null=True)),
                ('cost_of_cards', models.FloatField()),
                ('transport_fee', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('no_of_cards', models.IntegerField()),
                ('delivery_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'OnMyWay'), (2, 'Delivered')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Town')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
