# Generated by Django 2.2.3 on 2019-08-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_fname', models.CharField(max_length=100)),
                ('receiver_lname', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(null=True)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('pickup', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
